spring.application.name=aiassistant

# ================================
# MongoDB Configuration
# ================================
spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=${MONGODB_DATABASE}


# ================================
# AI / LLM Configuration
# This application is designed to be LLM-provider agnostic.
# Any LLM (Google Gemini, OpenAI, etc.) can be integrated
# by changing only the service implementation and config.
# ================================


# ================================
# Google Gemini Configuration
# ================================
# API key is injected from environment variables

gemini.api.key=${GEMINI_API_KEY}

# Base URL for Gemini Generative Language API
gemini.api.base-url=https://generativelanguage.googleapis.com/v1beta/

# Model used for content generation
gemini.model=models/gemini-2.5-flash


# ================================
# (Optional) OpenAI Configuration
# Disabled because billing is required
# ================================
# openai.api.key=${OPENAI_API_KEY}
# openai.api.url=https://api.openai.com/v1/chat/completions
# openai.model=gpt-4o-mini


management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.prometheus.enabled=true
management.endpoints.web.base-path=/actuator
management.endpoint.health.show-details=always